-- MySQL Script generated by MySQL Workbench
-- Thu Jan 13 19:19:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema accendoDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema accendoDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accendoDB` DEFAULT CHARACTER SET utf8 ;
USE `accendoDB` ;

-- -----------------------------------------------------
-- Table `accendoDB`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accendoDB`.`aluno` (
  `idAluno` VARCHAR(50) NOT NULL,
  `passwordAluno` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `sexo` VARCHAR(1) NULL,
  `idade` INT NULL,
  `etapa` VARCHAR(45) NULL,
  `serie` INT NULL,
  `rg` VARCHAR(9) NULL,
  `cpf` VARCHAR(11) NULL,
  `flag` TINYINT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accendoDB`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accendoDB`.`materia` (
  `idMateria` INT NOT NULL AUTO_INCREMENT,
  `nomeMateria` VARCHAR(45) NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accendoDB`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accendoDB`.`nota` (
  `idNota` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NULL,
  `ta` INT NULL,
  `materia_idMateria` INT NOT NULL,
  `aluno_idAluno` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idNota`, `materia_idMateria`, `aluno_idAluno`),
  INDEX `fk_nota_materia_idx` (`materia_idMateria` ASC) VISIBLE,
  INDEX `fk_nota_aluno1_idx` (`aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_nota_materia`
    FOREIGN KEY (`materia_idMateria`)
    REFERENCES `accendoDB`.`materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_aluno1`
    FOREIGN KEY (`aluno_idAluno`)
    REFERENCES `accendoDB`.`aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
