-- MySQL Script generated by MySQL Workbench
-- Fri Jan  7 14:25:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema accendoDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema accendoDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accendoDB` DEFAULT CHARACTER SET utf8 ;
USE `accendoDB` ;

-- -----------------------------------------------------
-- Table `accendoDB`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accendoDB`.`aluno` (
  `idAluno` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sexo` VARCHAR(1) NULL,
  `idade` INT NULL,
  `etapa` VARCHAR(45) NULL,
  `serie` INT NULL,
  `rg` VARCHAR(9) NULL,
  `cpf` VARCHAR(11) NULL,
  `flag` TINYINT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
